name: "CI Deep"

on:
  workflow_dispatch:
    inputs:
      unitFuzzRuns:
        default: "100000"
        description: "Unit: number of fuzz runs."
        required: false
      invariantRuns:
        default: "100"
        description: "Invariant runs: number of sequences of function calls generated and run."
        required: false
      invariantDepth:
        default: "100"
        description: "Invariant depth: number of function calls made in a given run."
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  test-unit:
    env:
      FOUNDRY_FUZZ_RUNS: ${{ inputs.unitFuzzRuns }}

    strategy:
      fail-fast: true

    runs-on: ubuntu-latest-64-cores
    steps:
      # Profile CPU and RAM usage to adjust machine size:
      # - uses: datadog/agent-github-action@v1.3
      #   with:
      #     api_key: ${{ secrets.DD_API_KEY }}

      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          cache: false # Requires a seed: https://github.com/foundry-rs/foundry-toolchain#fuzzing

      - name: Run tests
        run: forge test --no-match-path "test/invariants/**/*.sol"
        env:
          FOUNDRY_PROFILE: ci
          FORK_TESTS: false

  test-invariant:
    env:
      FOUNDRY_INVARIANT_DEPTH: ${{ inputs.invariantDepth }}
      FOUNDRY_INVARIANT_RUNS: ${{ inputs.invariantRuns }}

    strategy:
      fail-fast: true

    runs-on: ubuntu-latest-64-cores
    steps:
      # Profile CPU and RAM usage to adjust machine size:
      # - uses: datadog/agent-github-action@v1.3
      #   with:
      #     api_key: ${{ secrets.DD_API_KEY }}

      - uses: actions/checkout@v3

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly
          cache: false # Requires a seed: https://github.com/foundry-rs/foundry-toolchain#fuzzing

      - name: Run tests
        run: forge test --match-path "test/invariants/**/*.sol"
        env:
          FOUNDRY_PROFILE: ci
          FORK_TESTS: false
