name: push-to-main

on:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: push_to_main

jobs:
  check:
    strategy:
      fail-fast: true

    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
        env:
          FOUNDRY_PROFILE: push_to_main
          CENTRIFUGE_CHAIN_ORIGIN: ${{ secrets.CENTRIFUGE_CHAIN_ORIGIN }}
          MAINNET_RPC_URL: ${{ secrets.MAINNET_RPC_URL }}
          POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
          SETUP_TEST_DATA: false
